# Generated by Django 2.2.5 on 2019-12-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1', models.CharField(max_length=100)),
                ('service2', models.CharField(max_length=100)),
                ('service3', models.CharField(max_length=100)),
            ],
        ),
    ]
