# Generated by Django 2.2.5 on 2019-12-22 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='site_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
