# Generated by Django 2.2.5 on 2019-12-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191222_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='company_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rate',
            name='site_id',
            field=models.IntegerField(default=1),
        ),
    ]
