# Generated by Django 2.2.5 on 2019-12-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_delnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delnote',
            old_name='driver',
            new_name='veh_no',
        ),
    ]
