# Generated by Django 2.2.5 on 2019-12-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20191225_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='delnote',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
