# Generated by Django 2.2.5 on 2019-12-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_delnote_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='delnote',
            name='inv_id',
            field=models.IntegerField(default=0),
        ),
    ]
