# Generated by Django 2.2.5 on 2020-01-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_starting_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delnote',
            name='del_note_id',
            field=models.CharField(max_length=200),
        ),
    ]
