# Generated by Django 2.2.5 on 2019-12-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_id', models.IntegerField()),
                ('del_note_id', models.IntegerField()),
                ('rate_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_units',
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
