# Generated by Django 2.2.5 on 2020-05-02 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191228_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_details',
            name='rate',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_details',
            name='service',
            field=models.CharField(default='y', max_length=50),
            preserve_default=False,
        ),
    ]
