# Generated by Django 2.2.5 on 2020-02-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(default='Cash', max_length=300),
        ),
    ]
