# Generated by Django 2.2.5 on 2019-12-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='Unit_price',
        ),
    ]
